{
	"name": "Wikipedia",
	"version": "1.1.3",
	"icon": "fab fa-battle-net",
	"category": "information",
	"author": "Psychokiller1888",
	"maintainers": ["Jierka", "maxbachmann"],
	"desc": "Allows one to find informations about a topic on wikipedia",
	"aliceMinVersion": "1.0.0-a5",
	"systemRequirements": [],
	"pipRequirements": [
		"wikipedia",
		"BeautifulSoup4==4.6.3"
	],
	"conditions": {
		"lang": [
			"en",
			"fr",
			"de"
		],
		"online": true
	}
}
